--22:00
/* SCHEMA DE BANCO DE DADOS DO PROJETO INTEGRADOR 1 */
/* CRIADO POR: ELIEZER M. CAIXETA                   */
/* ALTERADO POR:            DATA:                   */

DROP TABLE IF EXISTS PACIENTE;
DROP TABLE IF EXISTS ENDERECO;
DROP TABLE IF EXISTS CIDADE;
DROP TABLE IF EXISTS ESTADO;
DROP TABLE IF EXISTS PAIS;
DROP TABLE IF EXISTS VEICULO;
DROP TABLE IF EXISTS AGENDAMENTO;
DROP TABLE IF EXISTS HOSPITAL;
DROP TABLE IF EXISTS RESPONSAVEL;
DROP TABLE IF EXISTS TIPO_DOENCA;
DROP TABLE IF EXISTS TIPO_ENCAMINHAMENTO;
DROP TABLE IF EXISTS TIPO_RESPONSAVEL;
DROP TABLE IF EXISTS AGENDAMENTO_RESPONSAVEL;
DROP TABLE IF EXISTS TIPO_REMOCAO;

--Tabela onde serão armazenados os dados sobre os paises
CREATE TABLE PAIS (
    PAIS_ID INTEGER    PRIMARY KEY ON CONFLICT ROLLBACK AUTOINCREMENT UNIQUE NOT NULL,
    NOME    TEXT (250) UNIQUE ON CONFLICT ROLLBACK NOT NULL,
    SIGLA   TEXT (3)   UNIQUE ON CONFLICT ROLLBACK NOT NULL
);

--Tabela onde serão armazenados os dados sobre os estados relativos aos países
CREATE TABLE ESTADO (
    ESTADO_ID INTEGER    PRIMARY KEY ON CONFLICT ROLLBACK AUTOINCREMENT UNIQUE ON CONFLICT ROLLBACK NOT NULL,
    PAIS_ID   INTEGER    CONSTRAINT [ESTADO#PAIS_FK] REFERENCES PAIS (PAIS_ID) NOT NULL,
    NOME      TEXT (250) UNIQUE  NOT NULL,
    SIGLA     TEXT (3)   NOT NULL 
);

--Tabela onde serão armazenados os dados sobre as cidades relativos aos estados
CREATE TABLE CIDADE (
    CIDADE_ID     INTEGER         PRIMARY KEY ON CONFLICT ROLLBACK AUTOINCREMENT UNIQUE NOT NULL,
    ESTADO_ID     INTEGER         CONSTRAINT [CIDADE#ESTADO_FK] REFERENCES ESTADO (ESTADO_ID) NOT NULL,
    NOME          TEXT (250)      NOT NULL,
    DISTANCIA_KM  NUMERIC (10, 2) NOT NULL,
    VALOR_PEDAGIO NUMERIC (10, 2) NOT NULL
);

--Tabela onde serão armazenados os dados sobre os endereços relativos às cidades
-- ESTA TABELA SERÁ EXCLUíDA
/*
CREATE TABLE ENDERECO (
    ENDERECO_ID INTEGER    PRIMARY KEY AUTOINCREMENT NOT NULL UNIQUE,
    CIDADE_ID   INTEGER    CONSTRAINT [ENDERECO#CIDADE_FK] REFERENCES CIDADE (CIDADE_ID) NOT NULL,
    LOGRADOURO  TEXT (400) NOT NULL,
    NUMERO      TEXT (20)  NOT NULL,
    COMPLEMENTO TEXT (50) 
);
*/

--Tabela
CREATE TABLE VEICULO (
    VEICULO_ID   INTEGER         PRIMARY KEY AUTOINCREMENT UNIQUE NOT NULL,
    MODELO        TEXT (250)      NOT NULL,
    PLACA         TEXT (20)       UNIQUE NOT NULL,
    CAPACIDADE    NUMERIC (3)     NOT NULL,
    MEDIA_CONSUMO NUMERIC (10, 2) NOT NULL
);

--Tabela
CREATE TABLE HOSPITAL (
    HOSPITAL_ID INTEGER    PRIMARY KEY AUTOINCREMENT UNIQUE NOT NULL,
    ENDERECO_ID  INTEGER    CONSTRAINT [HOSPITAIS#ENDERECO_FK] REFERENCES ENDERECO (ENDERECO_ID) NOT NULL,
    NOME         TEXT (250) UNIQUE NOT NULL
);

CREATE TABLE PACIENTE (
    PACIENTE_ID INTEGER PRIMARY KEY AUTOINCREMENT UNIQUE NOT NULL,
    CIDADE_ID INTEGER CONSTRAINT [PACIENTE#CIDADE_FK] REFERENCES CIDADE (CIDADE_ID) NOT NULL,
    HYGIA       TEXT (20)  NOT NULL,
    NOME        TEXT (250) NOT NULL,
    DATA_NASC   TEXT  NOT NULL,
    TEL_1       NUMERIC (11) NOT NULL,
    TEL_2       NUMERIC (11),
    LOGRADOURO  TEXT (400) NOT NULL,
    NUMERO      TEXT (20)  NOT NULL,
    COMPLEMENTO TEXT (50),
    CEP         TEXT (10)  
);

--Tabela usuário
CREATE TABLE USUARIO (
    USUARIO_ID          INTEGER PRIMARY KEY AUTOINCREMENT UNIQUE NOT NULL,
    SENHA               VARCHAR (128) NOT NULL,
    USERNAME            VARCHAR (150) NOT NULL UNIQUE,
    PRIMEIRO_NOME       VARCHAR (30)  NOT NULL,
    SOBRENOME           VARCHAR (100) NOT NULL,
    EMAIL               VARCHAR (250) NOT NULL,
    ATIVO               BOOL          NOT NULL
);

--Tabela
CREATE TABLE MOTORISTA (
    MOTORISTA_ID        INTEGER PRIMARY KEY AUTOINCREMENT UNIQUE NOT NULL,
    NOME                TEXT (50) UNIQUE NOT NULL,
    NUMERO_HABILITACAO  TEXT (250) NOT NULL,
    CARGA_HORARIA       NUMERIC (5, 2) NOT NULL
);

--Tabela
CREATE TABLE 
 (
    TIPO_DOENCA_ID INTEGER PRIMARY KEY AUTOINCREMENT UNIQUE NOT NULL,
    NOME           TEXT (50)    UNIQUE NOT NULL
);

--Tabela
CREATE TABLE TIPO_ENCAMINHAMENTO (
    TIPO_ENCAMINHAMENTO_ID INTEGER PRIMARY KEY AUTOINCREMENT UNIQUE NOT NULL,
    NOME                   TEXT (50) UNIQUE NOT NULL
);

--Tabela
CREATE TABLE TIPO_REMOCAO (
    TIPO_REMOCAO_ID INTEGER PRIMARY KEY AUTOINCREMENT UNIQUE NOT NULL,
    NOME            TEXT (50) UNIQUE NOT NULL
);

--Tabela
CREATE TABLE AGENDAMENTO (
    AGENDAMENTO_ID              INTEGER PRIMARY KEY AUTOINCREMENT UNIQUE NOT NULL,
    PACIENTE_ID                 CONSTRAINT [AGENDAMENTO#PACIENTE_FK] REFERENCES PACIENTE (PACIENTE_ID) NOT NULL,
    TIPO_ENCAMINHAMENTO_ID      CONSTRAINT [AGENDAMENTO#TIPO_ENCAMINHAMENTO_FK] REFERENCES TIPO_ENCAMINHAMENTO (TIPO_ENCAMINHAMENTO_ID) NOT NULL,
    TIPO_DOENCA_ID              CONSTRAINT [AGENDAMENTO#TIPO_DOENCA_FK] REFERENCES TIPO_DOENCA (TIPO_DOENCA_ID) NOT NULL,
    TIPO_REMOCAO_ID             CONSTRAINT [AGENDAMENTO#TIPO_REMOCAO_FK] REFERENCES TIPO_REMOCAO (TIPO_REMOCAO_ID) NOT NULL,
    HOSPITAL_ID                 CONSTRAINT [AGENDAMENTO#HOSPITAL_FK] REFERENCES HOSPITAL (HOSPITAL_ID) NOT NULL,
    VEICULO_ID                  CONSTRAINT [AGENDAMENTO#VEICULO_FK] REFERENCES VEICULO (VEICULO_ID) NOT NULL,
    RESPONSAVEL_PAC             TEXT (200) NOT NULL,
    USUARIO_ID                  CONSTRAINT [AGENDAMENTO#USUARIOFK] REFERENCES USUARIO (USUARIO_ID) NOT NULL,
    MOTORISTA_ID                CONSTRAINT [AGENDAMENTO#MOTORISTA_FK] REFERENCES MOTORISTA (MOTORISTA_ID) NOT NULL,
    ESTADO_GERAL_PACIENTE       TEXT (500) NOT NULL,
    DATA_REMOCAO                TEXT (20)  NOT NULL,
    SAIDA_PREVISTA              TEXT (20) NOT NULL,
    OBSERVACAO                  TEXT (500) NOT NULL,
    CUSTO_IFD                   NUMERIC (5, 2) NOT NULL,
    CUSTO_ESTADIA               NUMERIC (5, 2) NOT NULL
);